apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth-service:v1.0.2
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: metrics
      protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
