apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic
  template:
    metadata:
      labels:
        app: traffic
    spec:
      containers:
        - name: traffic
          image: traffic-analyzer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: traffic-analyzer
spec:
  selector:
    app: traffic
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
    - name: metrics
      protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
