apiVersion: apps/v1
kind: Deployment
metadata:
  name: firewall-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firewall
  template:
    metadata:
      labels:
        app: firewall
    spec:
      containers:
        - name: firewall
          image: firewall-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: firewall-service
spec:
  selector:
    app: firewall
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

